apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemonjeremy
spec:
  selector:
    matchLabels:
      app: pokemonjeremy
  template:
    metadata:
      labels:
        app: pokemonjeremy
    spec:
      containers:
      - name: pokemonjeremy
        image: dcmanik11/pokemonapi-syseng-miniproject:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        # livenessProbe:
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: "/v1/ping"
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
      # imagePullSecrets:
      #   - name: melissa-hol-group
---
apiVersion: v1
kind: Service
metadata:
  name: pokemonjeremy-svc
spec:
  selector:
    app: pokemonjeremy
  ports:
  - port: 80
    targetPort: 5000
