apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokeanary-ingress
spec:
  rules:
  - host: pokeanary.shamirhusein.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pokeanary-svc
            port: 
              number: 80
  ingressClassName: nginx